package id.lariss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CaseSizeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSizeAllPropertiesEquals(CaseSize expected, CaseSize actual) {
        assertCaseSizeAutoGeneratedPropertiesEquals(expected, actual);
        assertCaseSizeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSizeAllUpdatablePropertiesEquals(CaseSize expected, CaseSize actual) {
        assertCaseSizeUpdatableFieldsEquals(expected, actual);
        assertCaseSizeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSizeAutoGeneratedPropertiesEquals(CaseSize expected, CaseSize actual) {
        assertThat(expected)
            .as("Verify CaseSize auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSizeUpdatableFieldsEquals(CaseSize expected, CaseSize actual) {
        assertThat(expected)
            .as("Verify CaseSize relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSizeUpdatableRelationshipsEquals(CaseSize expected, CaseSize actual) {
        // empty method
    }
}
