package id.lariss.domain;

import static id.lariss.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAllPropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertOrderProductAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAllUpdatablePropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertOrderProductUpdatableFieldsEquals(expected, actual);
        assertOrderProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAutoGeneratedPropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(expected)
            .as("Verify OrderProduct auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductUpdatableFieldsEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(expected)
            .as("Verify OrderProduct relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e ->
                assertThat(e.getTotalPrice()).as("check totalPrice").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getTotalPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductUpdatableRelationshipsEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(expected)
            .as("Verify OrderProduct relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()))
            .satisfies(e -> assertThat(e.getProductDetails()).as("check productDetails").isEqualTo(actual.getProductDetails()));
    }
}
