package id.lariss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StrapColorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapColorAllPropertiesEquals(StrapColor expected, StrapColor actual) {
        assertStrapColorAutoGeneratedPropertiesEquals(expected, actual);
        assertStrapColorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapColorAllUpdatablePropertiesEquals(StrapColor expected, StrapColor actual) {
        assertStrapColorUpdatableFieldsEquals(expected, actual);
        assertStrapColorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapColorAutoGeneratedPropertiesEquals(StrapColor expected, StrapColor actual) {
        assertThat(expected)
            .as("Verify StrapColor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapColorUpdatableFieldsEquals(StrapColor expected, StrapColor actual) {
        assertThat(expected)
            .as("Verify StrapColor relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapColorUpdatableRelationshipsEquals(StrapColor expected, StrapColor actual) {
        // empty method
    }
}
