package id.lariss.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StrapSizeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapSizeAllPropertiesEquals(StrapSize expected, StrapSize actual) {
        assertStrapSizeAutoGeneratedPropertiesEquals(expected, actual);
        assertStrapSizeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapSizeAllUpdatablePropertiesEquals(StrapSize expected, StrapSize actual) {
        assertStrapSizeUpdatableFieldsEquals(expected, actual);
        assertStrapSizeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapSizeAutoGeneratedPropertiesEquals(StrapSize expected, StrapSize actual) {
        assertThat(expected)
            .as("Verify StrapSize auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapSizeUpdatableFieldsEquals(StrapSize expected, StrapSize actual) {
        assertThat(expected)
            .as("Verify StrapSize relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrapSizeUpdatableRelationshipsEquals(StrapSize expected, StrapSize actual) {
        // empty method
    }
}
